lib/bluecode_connector_web/router.ex
defmodule BluecodeConnectorWeb.Router do
  use BluecodeConnectorWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    # Out of scope for ECB Hackathon: adding basic auth, etc.
  end

  scope "/wizard", BluecodeConnectorWeb.Onboarding do
    pipe_through(:browser)

    get("/", WizardController, :index)
    get("/new", WizardController, :new)
    get("/callback", WizardController, :callback)
  end

  scope "/clearing/", BluecodeConnectorWeb.ClearingApi do
    pipe_through(:api)

    post("/payment", ClearingController, :payment)
  end
end

lib/bluecode_connector_web/controllers/onboarding/wizard_controller.ex
defmodule BluecodeConnectorWeb.Onboarding.WizardController do
  use BluecodeConnectorWeb, :controller

  alias BluecodeConnector.MappingTables
  alias BluecodeConnector.BankLambda.OauthClient
  alias BluecodeConnector.BankLambda.AispApiClient

  alias BluecodeConnector.Bluecode.ContractsApiClient

  def index(conn, %{"jwt" => jwt}) do
    wallet_id = extract_wallet_id(jwt)

    render(conn, "index.html", jwt: jwt, wallet_id: wallet_id)
  end

  def new(conn, %{"jwt" => jwt}) do
    contract_number = "anon_#{:crypto.rand_uniform(1_000_000, 9_000_000)}"

    MappingTables.create_account(%{
      "card_request_token" => jwt,
      "contract_number" => contract_number
    })

    url =
      OauthClient.authorize_url!([], %{
        contract_number: contract_number
      })

    redirect(conn, external: url)
  end

  def callback(conn, %{"code" => oauth_code, "contract_number" => contract_number}) do
    with account <- MappingTables.get_account_by!(contract_number: contract_number),
         {:ok, account} <- update_oauth_token(account, oauth_code),
         {:ok, account, account_name} <- update_account_iban(account) do
      # We have all information from Bank Lambda AISP. Now create connection to bluecode.

      # TODO: move into the with pipeline:
      create_bluecode_contract(account.contract_number)
      create_bluecode_card(account.contract_number, account.card_request_token, account_name)

      # TODO: don't, only for demonstration and debugging information.
      wallet_id = extract_wallet_id(account.card_request_token)

      render(
        conn,
        "success.html",
        access_token: account.oauth_token,
        account_name: account_name,
        contract_number: contract_number,
        wallet_id: wallet_id,
        iban: account.iban
      )
    end
  end

  defp update_oauth_token(account, code) do
    response =
      OauthClient.get_token!([code: code], %{
        contract_number: account.contract_number
      })

    {:ok, account} =
      MappingTables.update_account(account, %{
        oauth_code: code,
        oauth_token: response.token.access_token
      })

    {:ok, account}
  end

  defp update_account_iban(account) do
    {:ok, %{body: accounts}} =
      AispApiClient.new(%{access_token: account.oauth_token})
      |> AispApiClient.accounts()

    main_acct = List.first(accounts["accounts"])
    iban = main_acct["iban"]
    account_name = main_acct["name"]

    {:ok, account} = MappingTables.update_account(account, %{iban: iban})

    {:ok, account, account_name}
  end

  defp create_bluecode_contract(contract_number) do
    member_id = Application.get_env(:bluecode_connector, :bluecode_member_id)

    resp =
      contracts_api_client()
      |> ContractsApiClient.create_contract(%ContractsApiClient.Contract{
        contract_number: contract_number,
        member_id: member_id
      })

    # TODO: handle responses
    {:ok, resp}
  end

  defp create_bluecode_card(contract_number, card_request_token, display_name) do
    resp =
      contracts_api_client()
      |> ContractsApiClient.create_card(%{
        contract_number: contract_number,
        display_name: display_name,
        card_request_token: card_request_token
      })

    # TODO: handle responses
    {:ok, resp}
  end

  defp contracts_api_client() do
    bc_auth = Application.get_env(:bluecode_connector, :bc_auth)
    ContractsApiClient.new(bc_auth[:username], bc_auth[:password])
  end

  defp extract_wallet_id(jwt) do
    %JOSE.JWT{fields: payload} = JOSE.JWT.peek_payload(jwt)

    wallet_id =
      payload["wid"]
      |> String.trim_leading("wlt_")

    wids = String.split(wallet_id, "-")

    "#{hd(wids)}-...-#{List.last(wids)}"
  end
end

lib/bluecode_connector_web/views/onboarding/wizard_view.ex
defmodule BluecodeConnectorWeb.Onboarding.WizardView do
  use BluecodeConnectorWeb, :view
end

lib/bluecode_connector_web/templates/onboarding/wizard/index.html.eex
<div class="card">
  <div class="card-header">
    <strong>Authorization</strong>
  </div>
  <div class="card-body">
    <ul class="list list-unstyled">
      <li>🛒 POS Payments</li>
      <li>🎮 Ecommerce Payments</li>
    </ul>
    <br />
    <div>
      <input type="checkbox" name="terms" checked>
        Herewith you authorize Bank Lambda to make Instant payments in the Bluecode acceptance network
      <br>
    </div>
    <br />
    <p class="text-center">
    <%= link to: Routes.wizard_path(@conn, :new, jwt: @jwt), class: "btn btn-warning btn-lg" do %>
      <strong>Login with Bank Lambda</strong>
    <% end %>
    </p>

    <br />
    <p class="text-muted">
      <strong>Privacy:</strong>
      <br />
      No personal data is shared with Bluecode.
    </p>
  </div>
</div>
<br />
<br />
<br />
<br />
<pre>
<code>
Bluecode <-> Lambda Adapter:
- Wallet:   <%= @wallet_id %>
- Contract: ___

Lambda Adapter <-> Bank Lambda PSD2:
- Oauth Token: ___
- IBAN:        ___
</code>
</pre>

lib/bluecode_connector_web/templates/onboarding/wizard/success.html.eex
<div class="card">
  <div class="card-header">
    <strong>Successfully connected</strong>
  </div>
  <div class="card-body">
    You have successfully connected following bank accounts with Bluecode:

<br />
<br />
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Bluecode ID</th>
        <th>Lambda Account</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          Contract<br />
          <strong><%= @contract_number %></strong>
        </td>
        <td>
          <%= @account_name %>
          <br />
          <strong><%= String.slice(@iban || "DE0123213", 0, 6) %>...</strong>
        </td>
      </tr>
    </tbody>
  </table>
  </div>
  <div class="card-footer text-center">
    <a href="bluecode://closewebview" class="btn btn-primary"> Return to App </a>
  </div>
</div>


<br />
<br />
<br />
<br />
<hr>
<h6>Debug section </h6>
<pre>
<code>
Bluecode <-> Lambda Adapter:
- Wallet:   <%= @wallet_id %>
- Contract: <%= @contract_number %>

Lambda Adapter <-> Bank Lambda PSD2:
- OAuth Token: <%= String.slice(@access_token, 0, 10) <> "..." %>
- IBAN:        <%= @iban %>
</code>
</pre>